{{- if .Values.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "theabc-ingress-controller.fullname" . }}
  labels:
    app: {{ template "theabc-ingress-controller.name" . }}
{{ include "theabc-ingress-controller.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "theabc-ingress-controller.name" . }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.proxyUrl }}
    proxyUrl: {{ .Values.serviceMonitor.proxyUrl}}
    {{- end }}
    {{- if .Values.serviceMonitor.scheme }}
    scheme: {{ .Values.serviceMonitor.scheme }}
    {{- end }}
    {{- if .Values.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ .Values.serviceMonitor.bearerTokenFile }}
    {{- end }}
    {{- if .Values.serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml .Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    path: "/metrics"
{{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}
