apiVersion: v1
kind: Service
metadata:
  name: {{ include "theabc-ingress-controller.fullname" . }}
  labels:
    {{- include "theabc-ingress-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "theabc-ingress-controller.selectorLabels" . | nindent 4 }}
