apiVersion: v1
kind: Endpoints
metadata:
  name: baidu-com
  namespace: default
subsets:
- addresses:
  - ip: 36.152.44.96
  ports:
  - port: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baidu-com
  name: baidu-com
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    yarp.ingress.kubernetes.io/backend-protocol: 'http'
  name: baidu-com
  namespace: default
spec:
  ingressClassName: theabc
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: baidu-com
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls: []