apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theabc-ingress-controller.fullname" . }}
  labels:
    {{- include "theabc-ingress-controller.labels" . | nindent 4 }}
data:
  yarp.json: |
    {
      "Yarp": {
        "ControllerClass": "theabc.com/{{ .Values.yarp.controllerClass | default .Release.Name }}",
        "ServerCertificates": {{ .Values.yarp.serverCertificates }},
        "DefaultSslCertificate": "{{ .Values.yarp.defaultSslCertificateSecretName | default .Release.Namespace }}/{{ .Values.yarp.defaultSslCertificateSecretName}}",
        "ControllerServiceNamespace": "{{ .Release.Namespace }}",
        "ControllerServiceName": "{{ include "theabc-ingress-controller.fullname" . }}"
      }
    }